edition = "2018"
unstable_features = true

max_width = 120
fn_single_line = true
format_macro_matchers = true
format_macro_bodies = true
match_block_trailing_comma = true
merge_imports = true
overflow_delimited_expr = true
reorder_impl_items = true
use_small_heuristics = "Max"
